services:
  auth_pg:
    image: postgres
    container_name: auth_pg
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth_secret
      POSTGRES_DB: postgres
    volumes:
      - auth_pg:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    command: [ "postgres", "-c", "log_statement=all" ]
    networks:
      - auth-network

  auth-service:
    build:
      context: .
    ports:
      - "3000:3000"
    container_name: auth-service
    restart: on-failure
    networks:
      - auth-network
    environment:
      PG_DSN: ${PG_DSN}

volumes:
  auth_pg:

networks:
  auth-network: