services:
  auth-service:
    build:
      context: .
    ports:
      - "3000:3000"
    container_name: auth-service
    restart: on-failure
    environment:
      PG_DSN: ${PG_DSN}
      PRIVATE_SIGNING_KEY: ${PRIVATE_SIGNING_KEY}