services:
  auth_pg:
    image: postgres
    container_name: auth_pg
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth_secret
      POSTGRES_DB: postgres
    volumes:
      - auth_pg:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    command: [ "postgres", "-c", "log_statement=all" ]

  auth-service:
    build:
      context: .
    container_name: auth-service
    restart: on-failure

volumes:
  auth_pg: